### ISSUE TITLE
Project Data outside Plugin Dir

### ISSUE THREAD

**Issue by rawdlite** [kellerkinderDE/K10rProject#6]
i have included this plugin as a git submodule in my project repo.
This means after i checkout my code Snippets.php and the Migrations dir are empty and i have to copy/link my project specific Snippets.php and Migrations files in to the plugin path.
I would prefer when plugin code and data could reside in different path.
Does that make sense?

Cheers tom

**Comment by kleinmann** [comment]
Hi Tom! This plugin acts as a template for your project-specific copy and not to be used directly in projects. See also the installation information:

> This is a project specific plugin, so make sure every project has it's own copy of this base plugin.

So just include it as files instead of a git submodule and you should be able to change the files as you please :-)

**Comment by kleinmann** [comment]
I hope you had success in using this plugin :-) I'm closing this issue, please open another issue for any further questions.
